---
title: "p8105_hw5_rh3195"
author: "Ruijie He"
date: "2023-11-17"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)
library(viridis)
library(purrr)
library(dplyr)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Problem 1

### Import and clean data

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv", na = c("", "NA", "Unknown")) %>%
  mutate(
    city_state = str_c(city, state, sep = ", "),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
  filter(city_state != "Tulsa, AL") 

```

> The cleaned data frame has 52178 observations in uid, reported_date, victim_last, victim_first, victim_race, victim_age, victim_sex, city, state, lat, lon, disposition, city_state, resolution variables.

### Proportion of homicides unsolved in the city of Baltimore

```{r}
# Filter the dataset
baltimore_df = 
  homicide_df %>% 
  select(city_state, disposition, resolution) %>% 
  group_by(city_state) %>% 
  filter(city_state == "Baltimore, MD") %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolution == "unsolved"))

# Proportion test
baltimore_test = 
  prop.test(
    x = baltimore_df %>% pull(hom_unsolved),
    n = baltimore_df %>% pull(hom_total))

broom::tidy(baltimore_test) %>% 
  knitr::kable(digits = 3)
```

## Problem 2

### Import and combine data

```{r}
study_df =
  tibble(
    files = list.files("./data/study_data/"),
    path = str_c("./data/study_data/", files)) %>% 
  mutate(data = map(path, read_csv)) %>% 
  unnest() %>% 
  mutate(files=str_replace(files,".csv",""),
         group = case_when(
      stringr::str_detect(files, "con") ~ "control",
      stringr::str_detect(files, "exp") ~ "experimental")) %>% 
  pivot_longer(week_1 : week_8,
               names_to = "week",
               values_to = "value",
               names_prefix = "week_") %>% 
  mutate(week = as.numeric(week)) %>% 
  select(!path)
```

### Make spaghetti plot

```{r}
spaghetti_plot =
  study_df %>% 
  ggplot(aes(x = week, y = value, group = files, color = group)) +
    geom_line() +
  labs(title = "Observations Over Time",
       x = "Week",
       y = "Value")

print(spaghetti_plot)
```

> Comment


